### ISSUE TITLE
希望能从xib中加载cell

### ISSUE THREAD

**Issue by OxfordLing** [tbl00c/ZZFLEX#1]

**Comment by tbl00c** [comment]
目前我们的业务暂时没有用到xib、sb，后期我会调研相关

**Comment by chenchaohui6666** [comment]
很棒，要是能用xib注册cell就好了

**Comment by tbl00c** [comment]
已支持xib。

**Comment by chenchaohui6666** [comment]
感谢！辛苦了！正好我还在研究，向大神学习！




| |
chenchaohui6666
|
|
邮箱：chenchaohui6666@163.com
|

Signature is customized by Netease Mail Master

在2019年04月18日 12:44，李伯坤 写道：

Closed #1.
