### ISSUE TITLE
使用其他的正常，但是masonry不执行是为什么呀？

### ISSUE THREAD

**Issue by ylxieg** [tbl00c/ZZFLEX#10]

**Comment by ylxieg** [comment]
self.redView = self.view.addView(1)
    .backgroundColor([UIColor redColor])
    .masonry(^ (MASConstraintMaker *make) {
        make.edges.mas_equalTo(UIEdgeInsetsMake(10, 10, 10, 10));
    }).view;

pod install后。在controller里随便添加一个view。都不执行masonry。换成.frame 就可以

**Comment by ylxieg** [comment]
代码发你126邮箱了大神. 求指导

**Comment by tbl00c** [comment]
与ZZFLEX和Masonry的导入方式有关，如果全是pod方式导入，不是要使用 use framework!
