### ISSUE TITLE
tableView 如何设置header或footer的高度？

### ISSUE THREAD

**Issue by ylxieg** [tbl00c/ZZFLEX#11]
没有继承ZZFlexibleLayoutViewController,所以collectionView的sectionInsets无法使用。使用的tableView+ZZFlexAngel，无法设置tableView的header与footer高度。求指教

**Comment by tbl00c** [comment]
header、footer实现ZZFlexibleLayoutViewProtocol里面的方法即可

**Comment by EarthMass** [comment]
不能用masonry自适应高度吗，只能用 viewHeightByDataModel 这个方法去指定高度，如果是复杂的cell,计算比较麻烦

**Comment by tbl00c** [comment]
这样会对列表性能造成一些影响，与高度缓存配合也是可以考虑的。下次大版本会做尝试。
