### ISSUE TITLE
在controller中做下拉刷新的时候需要连同状态栏一起下拉？

### ISSUE THREAD

**Issue by derekzhan** [tbl00c/ZZFLEX#12]
在controller中做下拉刷新的时候需要连同状态栏一起下拉，如何能实现？如下图
![image](https://s2.ax1x.com/2019/08/16/mZrPt1.png)

期待你的回复，感谢你提供这么好用的工具

**Comment by derekzhan** [comment]
https://s2.ax1x.com/2019/08/16/mZrPt1.png

**Comment by tbl00c** [comment]
已邮件回复
