### ISSUE TITLE
ZZFlexibleLayoutFlowLayout不满足需求，该怎么使用其他的FlowLayout

### ISSUE THREAD

**Issue by lzc1022** [tbl00c/ZZFLEX#21]

**Comment by tbl00c** [comment]
[self.collectionView setCollectionViewLayout:YourLayout];

**Comment by lzc1022** [comment]
请教问题，请看商品列表界面描述



从QQ邮箱发来的超大附件

ZZFLEX.zip (15.35M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=083032368d666ec86eec0709153056180e54050e560252541a560453001d505107521f0f0406531a060601520353550101075602333a646d6d767e736b1e1e5e47300f&t=exs_ftn_download&code=702630d7
